source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/myiOSComponent/myRepo.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'TKSecureCategory_Example' do
  pod 'TKSecureCategory', :path => '../'

  target 'TKSecureCategory_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
    pod 'TKSecureModule', '~> 0.0.1db'
  end
end
